### PR TITLE
[Docs] Remove dashboard related content before code release

### PR DESCRIPTION
**Pull request by lingyielia**
## Description
- removed all dashboard related content
- it's still visible in the API reference though, as the code is in main

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Review by antonymilne — APPROVED** [review]

**Review by huong-li-nguyen — APPROVED** [review]

**Review by maxschulz-COL — CHANGES_REQUESTED** [review]
As per our chat

**Comment by stichbury** [comment]
Noted on Slack, but I think we should avoid rolling back these changes as there was quite a bit of re-org and rewording in the docs and not just the addition of these two files. I have an outstanding task to also clean up the structure of the Vizro-AI docs and I fear it could all get a bit complex (my poor 🧠 won't handle it).

Could we instead focus on making sure the links readers follow are typically going to the latest "stable" (ie released) docs as we intended. The way to do this:

1. search and replace https://vizro.readthedocs.io/projects/vizro-ai/en/latest/ for https://vizro.readthedocs.io/projects/vizro-ai/ so that users get the versioned/"stable" docs
2. search and replace https://vizro-ai.readthedocs.io/ for https://vizro.readthedocs.io/projects/vizro-ai/
3. Find any external links to Vizro-AI docs (e.g. links in README files rather than in built docs, links in blog posts, release notes, even on Slack) and fix them as per 1/2
4. TEST!

**Comment by maxschulz-COL** [comment]
> Noted on Slack, but I think we should avoid rolling back these changes as there was quite a bit of re-org and rewording in the docs and not just the addition of these two files. I have an outstanding task to also clean up the structure of the Vizro-AI docs and I fear it could all get a bit complex (my poor 🧠 won't handle it).
> 
> Could we instead focus on making sure the links readers follow are typically going to the latest "stable" (ie released) docs as we intended. The way to do this:
> 
> 1. search and replace https://vizro.readthedocs.io/projects/vizro-ai/en/latest/ for https://vizro.readthedocs.io/projects/vizro-ai/ so that users get the versioned/"stable" docs
> 2. search and replace https://vizro-ai.readthedocs.io/ for https://vizro.readthedocs.io/projects/vizro-ai/
> 3. Find any external links to Vizro-AI docs (e.g. links in README files rather than in built docs, links in blog posts, release notes, even on Slack) and fix them as per 1/2
> 4. TEST!

Hey, independently of you I took a stab, slightly different strategy, I tried to replace all links to latest with https://vizro-ai.readthedocs.io/ as that seems the safest option? See this PR: https://github.com/mckinsey/vizro/pull/623

The 5 links which I could not replace are shown below, they refer to specific sections, where we would need `stable` to work:
Screenshot 2024-08-08 at 13 52 06
image


@stichbury Any objects to merge [this PR](https://github.com/mckinsey/vizro/pull/623) quickly?

**Comment by stichbury** [comment]
I have no objections to hardcoded `latest` where you need it since, well, you need it! Those pages need to be changed as soon as anything changes in the references (or put on standby to change) so it's fine to do it, if a bit annoying to maintain.

I think we're agreed with the other and you're flipping your changes. Thanks for doing this so swiftly! Ping me on Slack and I'll approve so you can merge ASAP.

**Pull request closed without merging**
