### PR TITLE
vizro_ai_integration_tests

### PR DESCRIPTION
**Pull request by l0uden**
## Description
integration tests for checking correct response of vizro-ai

## Checklist

- [x] I have not referenced individuals, products or companies in any commits, directly or indirectly
- [x] I have not added data or restricted code in any commits, directly or indirectly
- [ ] I have updated the docstring of any public function/class/model changed
- [ ] I have added tests to cover my changes (if applicable)

## Types of changes

- [x] Docs/refactoring (non-breaking change which improves codebase)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by Anna-Xiong — COMMENTED** [review]
@l0uden  Hi Alex, can you add one small change of the dev version. @maxschulz-COL what would be the current version if we want to bump test pacakge? thank you!

**Comment by maxschulz-COL** [comment]
> @l0uden Hi Alexey, can you add one small change of the dev version. @maxschulz-COL what would be the current version if we want to bump test pacakge? thank you!

Wait I don't understand, what do you mean?

**Comment by Anna-Xiong** [comment]
> > @l0uden Hi Alexey, can you add one small change of the dev version. @maxschulz-COL what would be the current version if we want to bump test pacakge? thank you!
> 
> Wait I don't understand, what do you mean?

the test pypi version we want to update with the newest merge?

**Comment by maxschulz-COL** [comment]
Ah ok got it! I already published a `dev1` version earlier, so @l0uden can you make this `dev2`, just type `hatch version dev` twice

**Review by maxschulz-COL — APPROVED** [review]
Lgtm, please do not forget to update the `dev` version and to adjust the conditions under which this has to run

**Review by Anna-Xiong — APPROVED** [review]
LGTM, thank you!

**Comment by l0uden** [comment]
> adjust the conditions under which this has to run

What does it mean?

**Pull request merged**
