### PR TITLE
[Docs]: Fix capitalization of "Jupyter Notebook"

### PR DESCRIPTION
**Pull request by bhavanaeh**
## Description
As per issue https://github.com/mckinsey/vizro/issues/723: Standardizing capitalization of "Jupyter Notebook" throughout documentation
## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Comment by bhavanaeh** [comment]
Hello! I have made changes wherever applicable! 

Just wanted to point out that there seems to be two more occurrences where I could capitalize. Specifically [here](https://github.com/mckinsey/vizro/blob/main/vizro-core/src/vizro/models/types.py#L279), [here](https://github.com/mckinsey/vizro/blob/main/vizro-core/src/vizro/models/types.py#L395) and [here](https://github.com/mckinsey/vizro/blob/main/vizro-core/src/vizro/models/types.py#L396). These are all comments, do you still want me to change them? I tried changing them but it requires an entry to be made to the changelog because of which the `Checks for Vizro / checks-vizro-core (pull_request)` check fails. 

Additionally, I also found an an occurrence in the `vizro/vizro-core/changelog.md` but again touching that file causes the `Checks for Vizro / checks-vizro-core (pull_request)` to fail.

**Review by huong-li-nguyen — APPROVED** [review]
The change as you have it suffices :) 

However, you can also change it in the other places you mention. If you need to create a changelog file - this would have to be done via running `hatch run changelog:add` from either vizro-core or vizro-ai depending on where you added that change.

But I'll leave that up to you 👍 The most important change is the one in the official docs as you have it.

Could you rename your PR to: [Docs] Fix capitalization of "Jupyter Notebook"

**Review by lingyielia — APPROVED** [review]

**Comment by lingyielia** [comment]
> `Checks for Vizro / checks-vizro-core (pull_request)` check fails

Hi @bhavanaeh the `Checks for Vizro / checks-vizro-core (pull_request) check fails` is because you need to create a changelog file for your PR. So if you run `hatch run changelog:add` in codespaces, that should automatically create a changelog file you can push to your PR

**Comment by stichbury** [comment]
Thanks @bhavanaeh for your contribution! I made those other fixes you recommended and all is ready for merge when the tests are complete.

**Review by stichbury — APPROVED** [review]
Approved! Thank you so much ⭐ 💪 ⭐

**Pull request merged**
