### PR TITLE
[Docs] Fix capitalization for "python"

### PR DESCRIPTION
**Pull request by feridaaa**
## Description
To address https://github.com/mckinsey/vizro/issues/734

Changed instances of "python" to "Python" where appropriate in vizro-core and vizro-ai.

## Notice

- [x ] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
LGTM Thank you @feridaaa! 🏆

**Comment by stichbury** [comment]
@antonymilne Please can I get a review on this one? 🙏

**Review by antonymilne — APPROVED** [review]

**Review by antonymilne — COMMENTED** [review]
@stichbury done, but we appear to have a problem with vale on the authors file. Should we put a big ignore block in?

**Comment by stichbury** [comment]
> @stichbury done, but we appear to have a problem with vale on the authors file. Should we put a big ignore block in?

Yep, I've done that now. I need to check those vale issues as it's still flagging a python -> Python change as a suggestion/warning, but at least the error is now resolved so we can merge this when it passes.

**Pull request merged**
