### PR TITLE
[Docs] Link medium article as an example to docs

### PR DESCRIPTION
**Pull request by sulphatet**
## Description
Based on my conversation with @stichbury [here](https://github.com/mckinsey/vizro/issues/377), I would like to add this blog post to the list of community tutorials on Vizro. [This](https://medium.com/@saffand03/creating-custom-dashboards-with-vizro-a-comprehensive-guide-73c69c6f851e) is the article link.

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Comment by stichbury** [comment]
Thanks @sulphatet this is great! Nice post 🚀 

Have you considered syndicating it over onto DZone https://dzone.com/ and/or dev.to https://dev.to/ so that it gets even more traffic? You can use canonical links on both so that your Medium post gets the SEO score but raise the visibility of your authoring efforts.

**Review by stichbury — APPROVED** [review]
I'm happy to take this as a linked post. I think some of the SMEs in the team may have some suggestions for possible extension tasks/improvements but I think as a post it is fine to include in the docs as-is, so approving.

**Review by huong-li-nguyen — APPROVED** [review]
Hello @sulphatet,

First of all, thank you so much for your contribution! We always appreciate our users taking the initiative and creating tutorials, so I'm delighted to approve this PR and add the article link to our docs! 📖🚀

I’ve read through the article, and it’s great!⭐ I like the structure and how you start with Vizro's core foundations, such as components and filters, before deep-diving into customization, like layouts and custom charts.

Regarding the content, I have a small suggestion for simplification, as I think the current example on custom components is a bit more complex than necessary.

**Your current custom component:**
```jsx
class YearRangeSelector(vm.RangeSlider):
    type: Literal["year_range_selector"] = "year_range_selector"

    def build(self):
        range_slider_build_obj = super().build()
        range_slider_build_obj[self.id].min = 1990
        range_slider_build_obj[self.id].max = 2019
        range_slider_build_obj[self.id].value = list(range(1990,2020,1))
        range_slider_build_obj[self.id].allowCross = False
        range_slider_build_obj[self.id].marks = {i: {'label': "'{}".format(str(i)[-2:]), 
                                                     'style': {"fontSize": "10px"}} for i in range(1990, 2021, 2)}
        range_slider_build_obj[self.id].tooltip = {"always_visible": True,
                                                    "template": "{value}"
                                                   }
        return range_slider_build_obj
```

In general, you don’t need to hardcode values for “min”, “max”, “value”, and “marks” inside the build, as these should be configurable. 😊 If the tooltip and slider cross prevention aren’t essential, you could achieve the same with the standard RangeSlider, **avoiding the need for a custom component**:

```jsx
vm.RangeSlider(
                marks={
                    i: {"label": "'{}".format(str(i)[-2:]), "style": {"fontSize": "10px"}}
                    for i in range(min(df["year"]), max(df["year"]), 6)
                },
                step=6,
            )
```

Plugging into an app:

```jsx
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro

df = px.data.gapminder()

page = vm.Page(
    title="Range Slider",
    components=[
        vm.Graph(figure=px.box(df, x="continent", y="lifeExp", title="Equal Title One")),
    ],
    controls=[
        vm.Filter(
            column="year",
            selector=vm.RangeSlider(
                marks={
                    i: {"label": "'{}".format(str(i)[-2:]), "style": {"fontSize": "10px"}}
                    for i in range(min(df["year"]), max(df["year"]), 6)
                },
                step=6,
            ),
        )
    ],
)
dashboard = vm.Dashboard(pages=[page])
Vizro().build(dashboard).run()
```
Screenshot 2024-06-05 at 13 21 53

So for this example, you would **not need a custom component at all**. However, if you prefer creating a custom range slider to include the tooltip and prevent slider cross, you could use:

```jsx
class RangeSliderWithTooltip(vm.RangeSlider):
    type: Literal["range_slider_with_tooltip"] = "range_slider_with_tooltip"

    def build(self):
        range_slider_build_obj = super().build()
        range_slider_build_obj[self.id].allowCross = False
        range_slider_build_obj[self.id].tooltip = {"always_visible": True,
                                                    "template": "{value}"}
        return range_slider_build_obj
```

And then you can replace the Filter with your custom RangeSlider:

```jsx
 vm.Filter(
            column="year",
            selector=RangeSliderWithTooltip(
                marks={
                    i: {"label": "'{}".format(str(i)[-2:]), "style": {"fontSize": "10px"}}
                    for i in range(min(df["year"]), max(df["year"]), 6)
                },
                step=6,
            ),
        )
```

I think this simplification would not only reduce code, but it also makes it easier to understand why a custom component was necessary in the first place. 

Hope that helps! Let me know if you have any questions 😊

**Comment by sulphatet** [comment]
Hello @stichbury , Thanks a lot for letting me know about dzone and dev.to! These will be super useful for me!

@huong-li-nguyen thanks for your valuable input! 

Yes, since I was trying to focus on demonstrating the customizable aspect of Vizro and its powerful possibilities, I had decided on hard-coding all the features of the original Dash RangeSlider as I required🤔. However, to follow best practices, making these parameters configurable and simplifying the code as you've suggested is a great idea. I'll update the tutorial to reflect this approach, ensuring it’s more streamlined and easier to understand for users. Again, thanks a lot for your helpful suggestions!

**Comment by huong-li-nguyen** [comment]
> Yes, since I was trying to focus on demonstrating the customizable aspect of Vizro and its powerful possibilities, I had decided on hard-coding all the features of the original Dash RangeSlider as I required🤔. However, to follow best practices, making these parameters configurable and simplifying the code as you've suggested is a great idea. I'll update the tutorial to reflect this approach, ensuring it’s more streamlined and easier to understand for users. Again, thanks a lot for your helpful suggestions!


Sounds good! 🚀  I just helped you get the PR merged, because I think external contributors cannot click on the merge button 😄

**Pull request merged**
