### PR TITLE
[GHC] Refactor/remove legacy code 

### LINKED ISSUE #721: Remove `if __name__ == "__main__"` block from `_layout.py`
This is legacy code we don't want any more.

### PR DESCRIPTION
**Pull request by sylviezhang37**
## Description
Fixes #721 , removing legacy __name__ = "__main__" block

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Comment by lingyielia** [comment]
Thanks for contributing @sylviezhang37 ! Could you try check (click `Details` of the failing ones to see why) and fix the 3 failed CI? 😄 
1. Checks for Vizro / checks-vizro-core (pull_request) 
2. Lint / lint-vizro-all (pull_request) 
3. pre-commit.ci - pr

**Comment by sylviezhang37** [comment]
Hi @lingyielia , I think the issues are all resolved. Thanks for pointing them out!

**Review by antonymilne — APPROVED** [review]
Thank you very much for your contribution! 🙌 We are going to merge it today.

**Review by stichbury — APPROVED** [review]
LGTM ⭐

**Pull request merged**
