### PR TITLE
[Docs] Update `README.md` for style guide & basic readability

### PR DESCRIPTION
**Pull request by stichbury**
## Description
This PR updates the top-level README at a basic level to meet the style guide and tweak a few sections (making more of `vizro-ai` earlier on the page). It does not address core messaging changes as we're still discussing them.

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

### CODE REVIEW

**Review by maxschulz-COL — APPROVED** [review]
LGTM! Could you in future remember ticking the Box 😂  I know it's a pain, but we require it...

Will do for you this time

**Review by petar-qb — APPROVED** [review]
This README.md really looks better! 🥇 

QQ: Should we add some text before the "Live demo" png image? Do you think something like: `"Visit Vizro in action by clicking the following image or visiting https://www.mckinsey.com"` is necessary? 

The only reason I think we should emphasise that it's clickable is because we have a non-clickable "Examples" image above the "Live Demo" image.

QQ2: Also, do you think the "Examples" section is necessary anymore?

**Review by nadijagraca — APPROVED** [review]
LGTM. 🌟

**Comment by stichbury** [comment]
I have a linter issue with this PR because codespell is picking up a term in the Vale folder and trying to correct it (we need it be in Vale so it's spotted and flagged for, you guessed it, correction). How can I persuade codespell this is fine (e.g. filter out the `.vale` folder from scanning?). cc @huong-li-nguyen @l0uden 

```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

.vale/styles/Microsoft/Terms.yml:50: utilising ==> utilizing
```

**Comment by huong-li-nguyen** [comment]
> I have a linter issue with this PR because codespell is picking up a term in the Vale folder and trying to correct it (we need it be in Vale so it's spotted and flagged for, you guessed it, correction). How can I persuade codespell this is fine (e.g. filter out the `.vale` folder from scanning?). cc @huong-li-nguyen @l0uden

I just pushed the change :)

**Review by huong-li-nguyen — APPROVED** [review]

**Pull request merged**
